### ISSUE TITLE
Finalise the architecture of the app

### ISSUE THREAD

**Issue by RJ-Clegg** [RocketFanOrg/discussion#1]
We should finalise the various paradigms we will use for app. A good place to start would be to get the flow of data from / to the various screens. 

- [ ]  **Navigation** 

For this, my suggestion is using [Coordinators](https://www.swiftbysundell.com/posts/navigation-in-swift) with [Dependency injection](https://www.swiftbysundell.com/posts/dependency-injection-using-factories-in-swift) - using a `DependencyContainer `

This will also allow us to present any screen, anywhere in the app .  🚀 
I've used this paradigm very recently with great success 

- [ ]  **Data flows** - from and two the various views 

For screens we should think about how our data will flow through the app. I suggest the `MVVM` paradigm here. On top of this, I feel we should also use `Repositories` which the `ViewModels` will use as the source of data into them. 

It will be the job of the `Repository` to decided where and when to fetch data from (Either locally or through the api) 

With this approach, and using Dependency injection we should be able to test each component easily enough.

**Comment by squarefrog** [comment]
This seems like a valid approach. I've not read about `Repository` models, would you care to share an example?

**Comment by RJ-Clegg** [comment]
Sure, here's a quick example: 

-  Repository: 

```
class CurrentWeatherRepository {
    let webService = WebService()

    func getCurrentWeather(params: [String: String],
                           completion: @escaping (WeatherData?) -> Void,
                           failure: @escaping (Error) -> Void) {

        webService.makeGetRequest(url: APPURL.currentWeather, parameters: params, completion: { (response) in

         let weatherData // decode here 
            completion( watherData)
        }, failure: { (error) in
            failure(error)
        })
    }
}
```

- ViewModel 

```
  repository.getCurrentWeather(params: params, completion: { (data) in
            self.setupWeatherData(data)
       
        }, failure: { (error) in

            debugPrint(error)
        })
```

Notes: 

-  In our case, we will use  `Result` type, so there is only one closure and easier handling. 

-  Repository will either decode the data and return it or return and error 

-  Of course we can add other functions to the repository - to decide where to get the data from etc 

-  We would iuse DI to inject the repo into the ViewModel and the ViewModel injected into the ViewController - easy tests with mocks!

**Comment by squarefrog** [comment]
Lets do it 🚢

**Comment by RJ-Clegg** [comment]
I'll create a new issue to document the architecture and various paradigms and put it into a `ARCHITECTURE.md` file for documentation
